### ISSUE TITLE
Request for Windows binaries

### ISSUE THREAD

**Issue by rchastain** [farindk/morris#6]
Hello sir!

If you have time, could you please make Windows binaries of the latest version of the game (preferably in a ZIP file, without installer)?

On Linux I can build the application by myself, but on Windows it's too complicated for me.

Thanks.

**Comment by calcitem** [comment]
Dear Sir,

As the author of another open-source project called Sanmill, I noticed your request for a Windows binary of this game. I would like to kindly inform you that the author of this project, Morris, appears to have been inactive for an extended period, and the project may not be actively maintained at the moment.

If you are interested in exploring similar open-source alternatives, I invite you to take a look at Sanmill. Our project supports multiple platforms, including Windows, and we provide pre-built binaries for easy installation. You are more than welcome to try it out and see if it meets your needs.

I want to express my respect for Morris and the work they have done on this project. Open-source contributions like theirs are valuable to the community.

Thank you for your understanding, and I hope you find a suitable solution for your gaming interests.

Best regards,
Author of Sanmill

https://github.com/calcitem/Sanmill

**Comment by rchastain** [comment]
> If you are interested in exploring similar open-source alternatives, I invite you to take a look at Sanmill.

Thank you for your message. Your project looks very interesting indeed.

**Comment by farindk** [comment]
> If you have time, could you please make Windows binaries of the latest version of the game (preferably in a ZIP file, without installer)?

You can get v0.1 binaries for Windows from here:
https://nine-mens-morris.net/downloads.html

v0.2 only added the Sunmill board variant and v0.3 are only Linux specific changes. Hence, not much that you miss with that.

**Comment by rchastain** [comment]
Thank you for the information. Unfortunately I cannot use installers, but I will try to find a solution.

**Comment by farindk** [comment]
> Thank you for the information. Unfortunately I cannot use installers, but I will try to find a solution.

What is the issue with installers?

**Comment by rchastain** [comment]
I use Windows only at office, and I don't have admin rights. The execution of any _*.exe_ file coming from the web is blocked.

**Comment by farindk** [comment]
> The execution of any _*.exe_ file coming from the web is blocked.

Ok, but then a ZIP file will also not help. You need an executable that is signed with a developer certificate. I just got one for a commercial software that I am developing. For open source software, that is usually not feasible because of the costs and bureaucracy.

But right, that might actually be a reason to make a new Windows release, now that I can sign it.
I just don't have the time to work on that at the moment and the old development environment died with my old laptop.

**Comment by rchastain** [comment]
If the executable comes in a ZIP file, it works. Don't ask me why...

**Comment by farindk** [comment]
Some security loophole...

**Comment by rchastain** [comment]
Problem solved. I could extract the files from the installer (using [PeaZip](https://github.com/peazip/PeaZip)).

I close the issue.
